version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/openemr
      steps:
        - checkout
        - run: composer install
        - run: npm install
        - run: npm run build
        - run: composer global require phing/phing
        - run: $HOME/.config/composer/vendor/bin/phing vendor-clean
        - run: $HOME/.config/composer/vendor/bin/phing assets-clean
        - run: composer global remove phing/phing
        - run: composer dump-autoload -o
        - run: rm -fr node_modules || failTest=true
      environment:
        - DOCKER_DIR=nginx_80
        - OPENEMR_DIR=/usr/share/nginx/html/openemr
        - CHROMIUM_INSTALL="apt-get update; apt-get install -y zip libnss3 chromium"
        - SKIP_COMPOSER_PLATFORM_REQS=true
